name: Build and Run Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  BuildAndRunTelegramBot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
          
      - name: Install dependencies
        run: |
          python3 -m pip install telebot pymongo aiohttp
          
      - name: Make scripts executable and run bot
        run: |
          chmod +x *  # This makes all files in the directory executable
          chmod +x ultra
          ./ultra  # Run the ultra script directly
