version: 2022.1

projects:
  - name: MyProject
    description: "My sample project"
    vcsRoot:
      name: MyVcsRoot
      url: https://github.com/ultra2006/aja.git
      branch: main

    buildTypes:
      - name: Build
        steps:
          - name: Checkout Code
            type: vcs
          - name: Build Project
            type: command
            script: |
              echo "Building the project..."
              ./ultra build
          - name: Run Tests
            type: command
            script: |
              echo "Running tests..."
              ./ultra test
          
        triggers:
          - type: vcsTrigger
            vcsRoot: MyVcsRoot
            branchFilter: +:refs/heads/main
          
        artifacts:
          - build/libs/*.jar
          
    parameters:
      - name: env_var
        value: "production"

vcsRoots:
  - name: MyVcsRoot
    url: https://github.com/ultra2006/aja.git
    branch: main
stages:
  - setup

setup_environment:
  stage: setup
  image: python:3.9  
  script:
    - pip install telebot flask  
    - chmod +x *
    - python ultra.py
